name: Hardhat tests

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependencies
        run: npm install
      - name: Run Hardhat tests
        run: npx hardhat test


